### ISSUE TITLE
Installation problem requires ext-mongo >=0.9.0

### ISSUE THREAD

**Issue by OsAlex** [Brightcookie/lxHive#166]
Problem 1
    - Installation request for sokil/php-mongo 1.13.9 -> satisfiable by sokil/php-mongo[1.13.9].
    - sokil/php-mongo 1.13.9 requires ext-mongo >=0.9.0 -> the requested PHP extension mongo is missing from your system.
  Problem 2
    - Installation request for sokil/php-mongo-migrator 0.5 -> satisfiable by sokil/php-mongo-migrator[0.5].
    - sokil/php-mongo-migrator 0.5 requires ext-mongo >=0.9.0 -> the requested PHP extension mongo is missing from your system.

solution:
composer.phar require "alcaeus/mongo-php-adapter" --ignore-platform-reqs

**Comment by RoboSparrow** [comment]
@OAlex Thanks for documenting this. We are soon releasing lxHive 0.9.5. which will run on `ext-mongodb` and PHP 7, `sokil/php-mongo` will not be a dependency in the new release.

@leogaggl cc-ing you in, we need to announce the release
