### ISSUE TITLE
Correct some "bad request" responses

### ISSUE THREAD

**Issue by RoboSparrow** [Brightcookie/lxHive#20]
1. xAPI request without `Authorization` header:  _400 Bad Request_ 
   Currently _401_ - however, this is a bad request as a required header is missing
2. xAPI request with un-supported `X-Experience-API-Version` (e.g `99.99.9`): _400 Bad request_, _X-Experience-API-Version is not supported_
   Currently _404_, the suggested response is stolen from  https://lrs.adlnet.gov/xAPI/
3. xAPI request with clear (un-encoded) `Authorization` credentials (e.g. `Authorization:Basic non-extising:user`): `400` or `401` (?)
   Currently _500_
   This is an edge-case. ADL returns a 500 as well. Both systems seem to stumble over the decoding algorithm. However, I think we should be more specific as this is a common error. I suggest rejecting it with a 400, as this is technically a bad request.

Added Jasmine tests ('Bad requests' section).

**Comment by sraka1** [comment]
In regard to 1.; I think that 401 is an appropriate response if the Authorization header is missing.

Also supported by https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI-Communication.md#details-12

> `401 Unauthorized` - **Indicates that authentication is required**

**Comment by RoboSparrow** [comment]
I agree, 
however these are FAILS  from ADL the conformance test suite. 
Don't worry, I look into it.
