### ISSUE TITLE
Expose Custom headers not working 

### ISSUE THREAD

**Issue by medashiva** [Brightcookie/lxHive#231]
INSTALLED_APPS = (
    'corsheaders'
)
MIDDLEWARE_CLASSES  = 'corsheaders.middleware.CorsMiddleware',
CORS_ORIGIN_ALLOW_ALL = True
CORS_EXPOSE_HEADERS = ['header1']

i have added header1 in my CORS_EXPOSE_HEADERS but i am unable to see in xhr

<!DOCTYPE html>
<html>
<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script>
$(document).ready(function(){
    $("button").click(function(){
data = {
          UserName: "xxx",
          Password: "yyy"
        },

$.ajax({
            url: 'http://localhost/Sessions',
            type: 'post',
            dataType: 'json',
            contentType: 'application/json',
 xhrFields: {
       withCredentials: true
    },
	    crossDomain: true,
            success: function (data,xhr) {
                console.log(xhr) // headers comming as null
            },
            data: JSON.stringify(data)
        });

       
    });
});

    </script>
</head>
<body>

**Comment by RoboSparrow** [comment]
Hi, I am struggling to understand your issue. Is this lxHive related? This seems to be a Django CORS configuration problem. lxHive runs on PHP. Please provide more details so we can identify your problem
