### ISSUE TITLE
Issues accessing /public

### ISSUE THREAD

**Issue by zapur1** [Brightcookie/lxHive#3]
Hi,

I have gotten a fresh install going and I don't seem to be able to access /public . I've gone back over the installation steps and I followed them perfectly. I've also had a look through the Apache and PHP logs and then are no errors logged.

Any ideas of what may have gone wrong?

Thanks,
Zac

**Comment by sraka1** [comment]
It looks like you might've set your DocumentRoot to the project's root directory, instead of the `public` subdirectory.

So, if for example you cloned the repository to `/www/lxHive`, your DocumentRoot directive then needs to look like this: `DocumentRoot /www/lxHive/public`

Please confirm if this was indeed the issue and thanks for reporting.

**Comment by zapur1** [comment]
Hi,

Thanks for the help. I was already accessing it at www.****.com/public , I've changed around the DocumentRoot directive but there has been no change.

Interestingly before I changed around the DocumentRoot I could access /docs and see the documentation so that rules the likelihood of an Apache issue. The Apache and PHP logs still don't show anything useful, the access log does show a GET on / which shows it is getting somewhere.

Anymore ideas?
Thanks,
Zac

**Comment by RoboSparrow** [comment]
Hi zapur1,

there might be a misunderstanding. This is a REST Json API and not supposed to be a browsable website. Accessing `/public/index.php` directly will always output a `404` (and an empty screen). 

lxHive answers to a set of [defined endpoints](https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md), mainly for storing and retrieving statementes.

Here is a list of all endpoints our app answers to:
https://github.com/adlnet/xAPI-Spec/blob/1.0.3/xAPI.md#appendix-f-table-of-all-endpoints

You can test these endpoints in your browser, using tools like [Postman for Chrome](https://www.getpostman.com/) or [restClient for Firefox](http://restclient.net/)

Actually @sraka1, @leogaggl, we might need to add a little tutorial to our wiki.

The `docs` folder hold a compiled code documentation for developers and acts as standalone html.

Hope this helps

**Comment by zapur1** [comment]
Hi,

Yes that was an understanding on my side, I had a feeling that there was no browsable admin interface but then had a look through public/index.php and thought there actually might be.

Thanks for the help anyway, we will have a go at direct or xAPI calls to our lxHive install then.

Zac
