### ISSUE TITLE
Errors in the Wiki

### ISSUE THREAD

**Issue by rowild** [Brightcookie/lxHive#34]
Under xApi -> xAPI introduction, it says:
```
sponsored by the Office of the United Stated Under Secretary of Defense for Personnel and Readiness.
```
Shouldn't it read 
```
United States
```
?

Further down, under 'Using the configuration files', 2 methods of overwriting YAML configuration files are mentiones, which are actually only one method 'Config.production.yml':
```
The defaults are in Config.yml, however you can override them in Config.production.yml or Config.production.yml files.
```
What would the second one be?

Under 'Development guidelines', it reads:
```
[...] and fix any bugs you might.
```
I assume 'you might find' is, what you mean, right? :-)

**Comment by sraka1** [comment]
Thanks for the heads up, I went through the wiki and fixed all of the typos I was able to find (including the ones you mentioned).

Regarding the YAML file question, the second configuration file is "Config.development.yml", which is loaded when "development" mode is activated.

**Comment by rowild** [comment]
Thank you! That was quick! :-)

**Comment by leogaggl** [comment]
@rowild we don't waste time here ... ;-)

**Comment by RoboSparrow** [comment]
I liked the old version:)
