### ISSUE TITLE
500 status response for GET /statements with format: canonical

### ISSUE THREAD

**Issue by RoboSparrow** [Brightcookie/lxHive#42]
GET /statements

Here the params
```
{
            agent:{
                account: {
                    "homePage": "<url>",
                    "name": <name>"
                }
            },
            verb: 'http://adlnet.gov/expapi/verbs/approved',
            format: "canonical"
        }
```
Query (decoded)  
* http://<LRS>t/statements?agent={"account":{"homePage":"<url>","name":"<name>"}}&verb=http://adlnet.gov/expapi/verbs/approved&format=canonical

returns status `500 {"error_message":"Document has no method \"renderCanonical\""}`

see also: https://github.com/Brightcookie/lxHive/search?utf8=%E2%9C%93&q=canonical
This seems to be missing indeed.

**Comment by RoboSparrow** [comment]
Any progress? The error is due to a non-existant method PHP `renderCanonical` being called. A quick fix would be to insert this method and return a 'not implemented' header for now.

**Comment by sraka1** [comment]
A not implemented header was added in bcde3088be9fd3b6b880c279ec41ba44f7b976aa.

This task of actual implementation is now being tracked as two separate issues:
- #46 
- #47

**Comment by RoboSparrow** [comment]
reopen: ready for merge

**Comment by RoboSparrow** [comment]
@sraka what is the holdup in merging it down into master?

**Comment by sraka1** [comment]
This has been merged to master.
