### ISSUE TITLE
move twig .Cache folders into storage folders

### ISSUE THREAD

**Issue by RoboSparrow** [Brightcookie/lxHive#59]
This error stops oauth logins. when you vhost from user accounts (centos)

```
{"error_message":"Unable to create the cache directory (\/www\/lxHive\/src\/xAPI\/View\/V10\/OAuth\/.Cache\/5\/7)."}
````

We need to move the twig cache folders out into public/storage.

**Comment by sraka1** [comment]
Fixing.

**Comment by RoboSparrow** [comment]
attaching this for illustration the problem  - I just stumbled over it again on a fresh install

![selection_001](https://cloud.githubusercontent.com/assets/4016086/18538470/8d4f1620-7b4d-11e6-88f9-7ed9fb65d4b3.png)

**Comment by sraka1** [comment]
We might actually include the prebuilt cached templates in the repo. This is not a cache of any actual dynamic content - Twig just compiles the template from its syntax to a pure PHP file (template). This would however mean, that whenever we make any template changes we'd have to rebuild the cache (we will integrate this in the X CLI tool).

**Comment by RoboSparrow** [comment]
How about disabling Cache altogether? Quite an overkill to cache the tiny login page. I believe one can disable this via the `TwigEnvironment` instance.

**Comment by RoboSparrow** [comment]
btw, I question the point of using `slim/views` in general. i'd rather invoke twig directly where it's needed and have control over it in the actual view class
