### ISSUE TITLE
Installation on wamp

### ISSUE THREAD

**Issue by AnandKenta** [Brightcookie/lxHive#63]
i had configured and done the installation as it is. but when i try to run the localhost in port 82 using apache http server i receive a blank page with no error sign. 

**followed these steps:** 

Install dependencies via composer install.
Point your server's DocumentRoot directive to the public folder (httpd.conf) apache http server

**Sets up my database & client account:**
# Browse to application root
$ cd /<path_to_application_root>
# View available commands
$ ./X
# Set up database
$ ./X setup:db
# Set up OAuth scopes
$ ./X setup:oauth
# Create a new user
$ ./X user:create

**Comment by RoboSparrow** [comment]
Hi AnandKenta,

Can you please post the actual 500 error message and your OS? A blank page does not mean always that there is a "wihte screen of death" error. It could be just a misconfiguration in your Apache. (see below)

We have a more comprehensive installation tutorial in our Wiki:

https://github.com/Brightcookie/lxHive/wiki/Step-by-step:-Install-lxHive-and-setup-authentication-for-your-app

lxHive is a back-to-back application. So the *only page you can access via your browser* is the about page (like here; http://sandbox.experience.at/about)
At the stage you documented in your issue description you should be able to see the page.

For all other endpoints you need first to create  an authentication,  for example a basic token with `./X auth:basic:create`

A side note:

> Browse to application root
> $ cd /

This is a very unusual place for an web application root. I looks a bit like you placed lxHive outside the configured Apache `htdocs` location. Apache exposes only certain folders to http access (typically `/var/www/` but that really depends on your OS and  apache config). *Apache never exposes  `/`*,  unless you force it to. `/` should be never accessible via http requests, not even id development.

So in this  case it might be that your lxHive domain in Apache points to a different folder than where you located your code. You can find the document root  (entry folder) of your domain in the apache configuration file.  Example:

```bash
    ServerName my-lxhive.com #my custom lxhive domain
    ServerAlias www.my-lxhive.com
    DocumentRoot /var/www/html/lxHive/public # This is where Apchee expects the index.php to be located!
```

**Comment by AnandKenta** [comment]
Hi RoboSparrow,
   for your information i am configuring lxHive in windows 10 machine

**Comment by RoboSparrow** [comment]
This looks correct to me. There is (intentionally!) no root resource to answer for lxHive, so `http://localhost:82/` will return always `404`.  

As stated in the docs the way to test lxHive (and any other xAPI lrs) is the `/about` resource , ie. `http://localhost:82/about`

The `/about` is the only public resource on lxHive (i.e. callable in a browser)

Check if endpoint is up: https://github.com/Brightcookie/lxHive/wiki/Step-by-step:-Install-lxHive-and-setup-authentication-for-your-app#123-verify-your-server-is-set-up-correctly

Check if lxHive is ip: https://github.com/Brightcookie/lxHive/wiki/Step-by-step:-Install-lxHive-and-setup-authentication-for-your-app#17-test-the-lrs

**Comment by AnandKenta** [comment]
Hi RoboSparrow,
   Thanks for your help. i thought there might be a browsable admin page like other LRS. thanks for the help. 
Could you provide some JSON example statements for POST and GET request.
