### ISSUE TITLE
include creating filestore in installation process

### ISSUE THREAD

**Issue by RoboSparrow** [Brightcookie/lxHive#64]
@sraka1 I wonder if we can include the creation of the file storage folders (including perms) during the installation or setup process. This seems to be a frequent stumbling block.

As a paradigm I suggest the filestore should be always required, regardless if the user switches the config to `aws` or another adaptor. (writing cache files, like lock files, logs)

**1. option: composer script**

``` json

    "scripts": {
        "post-package-install": [
            "php -r \"mkdir('./storage/files/',0770, true);\""
        ]
    }
   // 0770 recommended by https://www.drupal.org/node/244924
```

**2. option during `./X` setup command via `League\Flysystem` adapter**

``` php
$config = Yaml::parse(<template-config.yml>);
$fs  = API\Util\Filesystem::generateAdapter($config['filesystem']); //creates folder(s)
```

Option 1 is IMO the most elegant. I tested both on apache/linux however I am not too sure if it works well with other env. Thoughts?

**Comment by sraka1** [comment]
What about if we put it in the repo and add a .gitkeep file in there?

**Comment by RoboSparrow** [comment]
>What about if we put it in the repo and add a .gitkeep file in there?
ownership and permissions
