### ISSUE TITLE
PHP 7 compatibility

### ISSUE THREAD

**Issue by limikael** [Brightcookie/lxHive#69]
Hi,

Are there any plans to support PHP 7? You would need to switch to the new mongodb driver in order to do so, as the old legacy driver is not supported in PHP7:

http://stackoverflow.com/questions/34569112/using-legacy-mongodb-driver-with-php7

**Comment by RoboSparrow** [comment]
Hi, 

yes , we are planning to switch to `mongodb` in one of our next releases. We are currently looking into performance implications. 

PHP7: support yes, requirement no (not yet). lxHive should work on PHP7 already, however it needs some deep unit testing. But the discussion is in flux. That really depends in how quickly it becomes ubiquitous with distros and providers. 

@leogaggl @sraka1

**Comment by sraka1** [comment]
PHP7 support is definitely being planned, however no release date has been set. But it's definitely becoming one of the priorities now.

A temporary workaround could also be to use a "polyfill", such as https://github.com/mongofill/mongofill, but the performance isn't good.

**Comment by limikael** [comment]
@sraka1 Thanks for the tip about mongofill! I might try that. Performance isn't an issue right now since we are in a development phase.

**Comment by RoboSparrow** [comment]
quick note abnout reverse compatibility (running <= lxHive 0.9.2 on PHP7 env)
largely untested, but seems to work

see https://github.com/alcaeus/mongo-php-adapter

```bash
composer require alcaeus/mongo-php-adapter --ignore-platform-reqs
````
