### ISSUE TITLE
oAuth login pure.css cdn broken

### ISSUE THREAD

**Issue by RoboSparrow** [Brightcookie/lxHive#8]
pure css cdn doesn't not support https (Error code: ssl_error_bad_cert_domain), so the css wont load

* https://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css

We need either to fetch it from a different cdn or  include it locally.

Options: 

* replace link with one of the other supported cdn's: http://purecss.io/customize/
* download rollup and include it locally: http://yui.yahooapis.com/pure/0.6.0/pure-min.css
* download/bower release package and include pure.min.css locally

This issue actually relates to a discussion we had about allowing LRS owners to plug-in their own theme/branding of OAuth, so maybe we tackle issue and enhancement in 0.9.1.

* expose a number of twig vars to config.yaml
* expose logo image destination to config.yaml
* provide a custom.css overwrite path and custom.js  path

**Comment by sraka1** [comment]
- expose logo image destination to config.yaml
   - provide a custom.css overwrite path and custom.js path

This is already implemented.


   - expose a number of twig vars to config.yaml

Which Twig vars for example?


Will also change CDM (SSL) and apply.

torek, 14. julij 2015 je oseba Joerg Boeselt <notifications@github.com
<javascript:_e(%7B%7D,'cvml','notifications@github.com');>> napisala:

> Assigned #8 <https://github.com/Brightcookie/lxHive/issues/8> to @sraka1
> <https://github.com/sraka1>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Brightcookie/lxHive/issues/8#event-354949704>.
>


-- 
Lp,
Jakob

**Comment by RoboSparrow** [comment]
>  Which Twig vars for example?

* brandName (text)
* brandImage (path)
* pageTop (below, h1, markup)
* formTop(text)
* formBottom (above submit button, text)
* pageFooter (markup)

**Comment by RoboSparrow** [comment]
Maybe the better way would be:

* expose optional template replacement path(s) to config.yaml
* provide example templates with the required vars.
* onRequest: check if custom tpl exists and include this instead of the lxHive template

This way the owner has full freedom to customize markup and content of the template and can also replace/extends css and js. Maybe we can even omit the config and do the check by default (for a defined user theme directory)

What do you think?

**Comment by RoboSparrow** [comment]
Closing this. Resolved for this milestone. Extended theme configuration: 0.9.2
