### ISSUE TITLE
Which xAPI version does lxHive support

### ISSUE THREAD

**Issue by datenwort** [Brightcookie/lxHive#94]
It is not clear to me which spec lxHive supports?
In the README.md are mentioned 2 different specs.

Is it 1.0.2 or 1.0.3?

**Comment by sraka1** [comment]
Hey @datenwort,

as written in the README, we currently supports xAPI specs <= 1.0.2 (so including 1.0.2).

We are working on 1.0.3 support, including a big refactoring effort to make everything faster and PHP7 compliant.

**Comment by RoboSparrow** [comment]
@datenwort 1.0.3 is pretty new and we are working on the tests. However, there are no breaking changes between 1.0.2 and 1.0.3 you should be fine in 99,5 % of all cases. 

There are two options to work around this:

1) You can just send 1.0.3 statements with the default configuration and using the `X-Experience-API-Version: 1.0.2` header
2)You can enable 1.0.3 support by editing the Config.yml

```yml
...
xAPI:
    latest_version: 1.0.3
...
   supported_versions: [1.01., 1.0.2, 1.0.3]
```

Let us know if you encounter any issues.

**Comment by RoboSparrow** [comment]
closing this
